micronaut:
  application:
    name: productSearchBackend
  server:
    port: 9000
    cors:
      enabled: true
      configurations:
        web:
          allowedOrigins:
            # TODO: Fix cors issue for production.
            - "http://localhost:5000"
