version: "3.8"

services:
  client:
    build:
      context: ./client
      args:
        - SERVER_URL=$SERVER_URL
    env_file:
      - .env
    depends_on:
      - server
      - service-registry
    ports:
      - "80:80"
  server:
    build:
      context: ./server
      args:
        - CLIENT_URL=$CLIENT_URL
    env_file:
      - .env
    ports:
      - "8080:8080"
  service-registry:
    build:
      context: ./service-registry
    env_file:
      - .env
    ports:
      - "8090:8090"
