micronaut:
  application:
    name: server
  router:
    static-resources:
      default:
        enabled: true
        mapping: "/assets/**"
        paths: "classpath:public"

jackson:
  serializationInclusion: ALWAYS
